# This is a basic workflow to help you get started with Actions

name: Nightly build of develop

on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      uploadURL: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
      # Create Tag by https://stackoverflow.com/a/64970393  
      - name: Checkout nightly build-repo
        uses: actions/checkout@v2
        with:
          repository: negue/meme-box-nightly
          path: nightly_repo 
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - name: Use Node.js 12.16.2
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Get current date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=TAG_NAME::nightly${date}"
          echo "::set-output name=RELEASE_NAME::nightly-release-${date}"

      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Create version_info.json
        uses: schdck/create-env-json@v1
        id: create-env
        with:
          file-name: './src/version_info.json'
          VERSION_TAG: ${{ steps.vars.outputs.TAG_NAME }}
          COMMIT: ${{ steps.vars.outputs.sha_short }}
          BUILD_TIME: ${{ steps.current-time.outputs.time }}
          BRANCH: ${{ steps.vars.outputs.branch }}

      - name: Create tag in public repository
        run: |
          cd ${{github.workspace}}/nightly_repo
          git tag ${{ steps.vars.outputs.TAG_NAME }}
          git push --tags --porcelain
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.TAG_NAME }}
          release_name: ${{ steps.vars.outputs.RELEASE_NAME }}
          draft: false
          prerelease:  true
          repo: meme-box-nightly
      - name: Upload Release Asset Windows Headless
        id: upload-release-asset-exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./release/out/memebox.exe
          asset_name: memebox-headless.exe
          asset_content_type: application/vnd.microsoft.portable-executable

